markdown: marku
pygments: true
url: http://0.0.0:4000
ftp_host: itmbs.com
ftp_dir: /public_html/blog.wikimatze.de/
ineturl: http://blog.wikimatze.de
permalink: /:title.html
author: @wikimatze
email: matthias.guenther@wikimatze.de 
fullname: Günther
title: wikimatze
build: 6-24-2011
page: 8
images: 1
links: 54
meta_robots: noodp, nodyr
pdfdir: pdf
exclude: ["Rakefile", "README", "pdf", "config", "to_do.txt"]
